export const englishDailyMissions = [
  {
    id: "deadline-negotiation",
    scene: "Project deadline negotiation",
    role: "You are speaking to a project lead",
    pressure: "The deadline is tomorrow, but one dependency is still unstable.",
    opening: "We still need the final build tomorrow. What exactly is blocking you, and what can you commit to instead?",
    listeningQuestion: "What does the project lead need from you?",
    choice: "A clear blocker, its impact, and a realistic alternative commitment.",
    alternative: "A simple apology without proposing a plan.",
    task: "Negotiate a realistic plan without sounding defensive.",
    prompt: "Explain the blocker, its consequence, and the alternative you can commit to.",
    moves: ["state the constraint", "explain why it matters", "offer a concrete trade-off"],
    frame: "The main constraint is ___, which means ___. Rather than ___, I can commit to ___.",
    model: "The main constraint is the unstable payment integration, which means a rushed release could corrupt customer records. Rather than ship every feature tomorrow, I can deliver the tested core flow and move reporting to Friday.",
    refinement: "Make the causal link and the alternative commitment explicit.",
    chunk: "The main constraint is…, which means… Rather than…, I can…",
    intent: "negotiate a deadline with evidence and a concrete alternative",
    changedContext: "vendor delivery negotiation",
  },
  {
    id: "defend-recommendation",
    scene: "Design review",
    role: "You are defending a recommendation to skeptical colleagues",
    pressure: "A colleague prefers the cheaper option and challenges your reasoning.",
    opening: "Your proposal costs more and takes longer. Why should the team choose it?",
    listeningQuestion: "What kind of answer will persuade the team?",
    choice: "A recommendation supported by criteria, evidence, and a trade-off.",
    alternative: "Repeating that your option is simply better.",
    task: "Defend a decision while acknowledging its downside.",
    prompt: "Give your recommendation, two reasons, and one limitation you accept.",
    moves: ["take a position", "support it with evidence", "acknowledge a limitation"],
    frame: "I recommend ___ for two reasons. First, ___. Second, ___. The trade-off is ___, but ___.",
    model: "I recommend the modular design for two reasons. First, it isolates failures during testing. Second, it lets us replace one component without redesigning the system. The trade-off is higher upfront cost, but it reduces integration risk later.",
    refinement: "Use signposting so the listener can follow the structure of your argument.",
    chunk: "I recommend… for two reasons. The trade-off is…, but…",
    intent: "defend a recommendation with evidence and qualification",
    changedContext: "budget review",
  },
  {
    id: "explain-complex-idea",
    scene: "Explain your work to a non-specialist",
    role: "You are talking to an intelligent friend outside your field",
    pressure: "They lose interest when the explanation becomes jargon-heavy.",
    opening: "I understand the words individually, but I still do not see why this technology matters in practice.",
    listeningQuestion: "What does your listener need next?",
    choice: "A plain-language mechanism, a concrete example, and the practical consequence.",
    alternative: "A more detailed list of specialist terms.",
    task: "Make a complex idea understandable without making it inaccurate.",
    prompt: "Explain one technical idea using a mechanism, an analogy, and a real consequence.",
    moves: ["describe how it works", "give an analogy or example", "state why it matters"],
    frame: "At a basic level, ___. You can think of it like ___. This matters because ___.",
    model: "At a basic level, a world model predicts how a situation may change after an action. You can think of it like a mental simulator that tests several moves before choosing one. This matters because a robot can avoid costly mistakes in the real world.",
    refinement: "Lead with the mechanism, then use the analogy to clarify rather than replace it.",
    chunk: "At a basic level… You can think of it like… This matters because…",
    intent: "explain a complex mechanism clearly to a non-specialist",
    changedContext: "conference networking",
  },
  {
    id: "polite-disagreement",
    scene: "Cross-functional meeting",
    role: "You disagree with a senior colleague",
    pressure: "You need to protect the relationship while challenging the plan.",
    opening: "I think we should launch now and fix the measurement problem later. Do you agree?",
    listeningQuestion: "What is the strongest professional response?",
    choice: "Recognize the goal, identify the risk, and propose a testable adjustment.",
    alternative: "Say yes to avoid tension.",
    task: "Disagree clearly without becoming confrontational.",
    prompt: "Acknowledge the goal, challenge one assumption, and propose a safer next step.",
    moves: ["show alignment", "name the concern", "offer a constructive alternative"],
    frame: "I agree that ___ matters. My concern is ___ because ___. Could we ___ before we commit?",
    model: "I agree that speed matters. My concern is that launching without reliable measurement will hide whether the change actually works. Could we run a limited release with two success metrics before we commit to the full rollout?",
    refinement: "Separate agreement with the goal from disagreement with the proposed method.",
    chunk: "I agree that… My concern is… Could we…?",
    intent: "disagree politely and propose a testable alternative",
    changedContext: "research collaboration",
  },
  {
    id: "story-with-point",
    scene: "Dinner with new friends",
    role: "Someone asks about a surprising experience",
    pressure: "A one-line answer will kill the conversation.",
    opening: "What is something that went wrong recently but taught you something useful?",
    listeningQuestion: "What will keep this social story engaging?",
    choice: "Set the scene, describe the turning point, and end with what changed.",
    alternative: "Give only the final lesson.",
    task: "Tell a compact story that gives the listener something to react to.",
    prompt: "Describe the situation, the unexpected turn, and what you learned.",
    moves: ["set the scene", "show what changed", "land on a meaningful point"],
    frame: "At first, ___. Then, unexpectedly, ___. What I took from it was ___.",
    model: "At first, I thought the presentation had gone badly because the audience asked almost no questions. Then, unexpectedly, three people contacted me afterward with detailed comments. What I took from it was that silence does not always mean disinterest.",
    refinement: "Use time markers to make the change in the story easy to follow.",
    chunk: "At first… Then, unexpectedly… What I took from it was…",
    intent: "tell a concise story with a turning point and reflection",
    changedContext: "team retrospective",
  },
  {
    id: "handle-service-problem",
    scene: "Hotel problem-solving",
    role: "You need help, but the first solution is not acceptable",
    pressure: "The staff member is polite but offers only a partial fix.",
    opening: "I am sorry about the noise. We cannot change your room, but we can offer breakfast. Would that work?",
    listeningQuestion: "What should you do instead of answering only yes or no?",
    choice: "Recognize the offer, explain the remaining impact, and request a workable solution.",
    alternative: "Repeat that the situation is bad.",
    task: "Reject a partial solution while staying calm and specific.",
    prompt: "Acknowledge the offer, explain why it does not solve the problem, and request an alternative.",
    moves: ["acknowledge", "explain the unresolved need", "make a specific request"],
    frame: "I appreciate ___. However, that would not solve ___ because ___. Would it be possible to ___?",
    model: "I appreciate the breakfast offer. However, that would not solve the sleep problem because I have an early presentation tomorrow. Would it be possible to arrange a quieter room after the next checkout or provide access to another property?",
    refinement: "Use “however” to make the rejection clear without making it hostile.",
    chunk: "I appreciate… However, that would not solve… Would it be possible to…?",
    intent: "resolve a service problem with calm, specific negotiation",
    changedContext: "airline disruption",
  },
  {
    id: "give-feedback",
    scene: "Feedback to a teammate",
    role: "You are helping a capable colleague improve",
    pressure: "The work has a real weakness, but vague criticism will not help.",
    opening: "You said the draft was not convincing. Which part should I change, and why?",
    listeningQuestion: "What makes feedback actionable?",
    choice: "A specific observation, its effect, and a concrete revision.",
    alternative: "A general judgment such as “make it clearer.”",
    task: "Give direct feedback that the other person can act on.",
    prompt: "Identify one issue, explain its effect on the reader, and suggest a revision.",
    moves: ["name observable evidence", "explain the effect", "suggest a concrete change"],
    frame: "In the section where ___, I noticed ___. This makes it difficult to ___. I suggest ___.",
    model: "In the section where you compare the two approaches, I noticed that the evaluation criteria change halfway through. This makes it difficult to understand why the second option wins. I suggest using the same three criteria in a short comparison table.",
    refinement: "Describe what you observed before you evaluate it.",
    chunk: "I noticed… This makes it difficult to… I suggest…",
    intent: "give specific, actionable feedback",
    changedContext: "peer review response",
  },
  {
    id: "choose-under-uncertainty",
    scene: "Decision under uncertainty",
    role: "The team needs your judgment before all data is available",
    pressure: "Waiting has a cost, but acting early also creates risk.",
    opening: "We do not have complete evidence. Should we decide now or wait another month?",
    listeningQuestion: "What is more useful than a bare yes or no?",
    choice: "A conditional decision based on risk, missing evidence, and a trigger for reassessment.",
    alternative: "Pretending the uncertainty does not exist.",
    task: "Make a qualified decision without sounding indecisive.",
    prompt: "State what you would do now, what uncertainty matters, and what would change your mind.",
    moves: ["make a provisional decision", "name the key uncertainty", "define a revision trigger"],
    frame: "Given what we know, I would ___. The main uncertainty is ___. I would reconsider if ___.",
    model: "Given what we know, I would run a limited pilot now rather than wait. The main uncertainty is whether the result holds for larger customers. I would reconsider a full launch if the pilot shows higher support costs than expected.",
    refinement: "A conditional decision can be decisive when the conditions are explicit.",
    chunk: "Given what we know… The main uncertainty is… I would reconsider if…",
    intent: "make and qualify a decision under uncertainty",
    changedContext: "research roadmap",
  },
];

const dayIndex = (day) => {
  const parsed = Date.parse(`${day}T00:00:00Z`);
  return Number.isFinite(parsed) ? Math.floor(parsed / 86_400_000) : 0;
};

export function selectDailyMission(day, targetLanguage = "English") {
  if (targetLanguage !== "English") return null;
  const index = ((dayIndex(day) % englishDailyMissions.length) + englishDailyMissions.length)
    % englishDailyMissions.length;
  return englishDailyMissions[index];
}

export function assessComplexEnglish(text) {
  const normalized = String(text || "").trim();
  const words = normalized.match(/[A-Za-z]+(?:['’-][A-Za-z]+)*/g) || [];
  const escape = /^(yes|no|maybe|i\s+(?:do not|don't)\s+know|not sure|i agree|i disagree)[.!?]?$/i.test(normalized);
  const hasReasoning = /\b(because|since|which means|so that|therefore|however|although|but|rather than|for example|for instance|the reason|the trade-off|if)\b/i.test(normalized);
  const ready = !escape && words.length >= 12 && hasReasoning;
  return {
    ready,
    escape,
    wordCount: words.length,
    missing: [
      ...(words.length < 12 ? ["at least 12 words"] : []),
      ...(!hasReasoning ? ["a reason, example, consequence, or contrast"] : []),
    ],
  };
}
